MyLibraryGUI/Models/Book.cs
using MyLibrary.Interfaces;
using System.ComponentModel.DataAnnotations;

namespace MyLibrary.Models
{
    public class Book:iBook
    {
        [Key]
		public int BookId { get; set; }
		public string Name { get; set; }
		public string Author { get; set; }
        public int? BorrowerId { get; set; }
    }
}

MyLibraryGUI/Models/LinkClass.cs
namespace MyLibrary.GUI.Models
{
    public class LinkClass
    {
        public string Text { get; set; }
        public string Url { get; set; }
        public int? Bookid { get; set; }
        public int? Borrowerid { get; set; }
        public LoanClass Loanclass { get; set; }
    }
}

MyLibraryGUI/Models/LoanClass.cs
namespace MyLibrary.GUI.Models
{
    public class LoanClass
    {
        public int BookId { get; set; }
        public int UserId { get; set; }
    }
}

MyLibraryGUI/Components/ShowLoanLinkViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyLibrary.GUI.Models;

namespace MyLibrary.Components
{
    public class ShowLoanLinkViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(LoanClass loanClass)
        {
            var linkClass = new LinkClass();
            linkClass.Text = "Låna";
            linkClass.Url = "/Lend";
            linkClass.Bookid = loanClass.BookId;
            linkClass.Borrowerid = loanClass.UserId;
            return View("Default", linkClass);
        }
    }
}

MyLibraryGUI/Components/ShowReturnLinkViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyLibrary.GUI.Models;

namespace MyLibrary.Components
{
    public class ShowReturnLinkViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(LoanClass loanClass)
        {
            var linkClass = new LinkClass();
            linkClass.Text = "Lämna tillbaka";
            linkClass.Url = "/Return";
            linkClass.Bookid = loanClass.BookId;
            return View("Default", linkClass);
        }
    }
}

MyLibraryGUI/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace MyLibraryGUI.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

MyLibraryGUI/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using MyLibrary.Models;

namespace MyLibraryGUI.Pages
{
    public class IndexModel : PageModel
    {
        //private readonly ILogger<IndexModel> _logger;
        //[Required]
        //[BindProperty]
        //public string SearchString { get; set; }
        public List<Book> bookList { get; set; }
        //public IndexModel(ILogger<IndexModel> logger)
        //{
        //    _logger = logger;
        //}
        [TempData]
        public string SearchString { get; set; }

        //public void OnGet()
        //{
        //if(SearchString != null)
        //{
        //    return RedirectToPage("/SearchResult");
        //}
        //return Redirect("~/");


        //HttpClient client = new HttpClient();
        //client.BaseAddress = new Uri("https://localhost:7034/");
        //HttpResponseMessage message = client.GetAsync("api/Users").Result;
        //string returnText = message.Content.ReadAsStringAsync().Result;

        //message = client.GetAsync("api/Books").Result;
        //returnText = message.Content.ReadAsStringAsync().Result;

        //List<Book> bookList = new List<Book>();
        //bookList =
        //    JsonSerializer.Deserialize<List<Book>>(returnText);
        //}

        public void OnGet()
        {
  
        }

        public IActionResult OnPost()
        {
            SearchString = Request.Form["SearchString"];
            return RedirectToPage("/SearchResult");
        }
    }
}

MyLibraryGUI/Pages/Lend.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyLibrary.GUI.Pages
{
    public class LendModel : PageModel
    {
        public void OnGet(int book, int user)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:7034/");
            //https://localhost:7034/api/Books/Loans/3/1
            HttpResponseMessage message = client.GetAsync("api/Books/Loans/" + book + "/" + user).Result;
            string returnText = message.Content.ReadAsStringAsync().Result;
        }
    }
}

MyLibraryGUI/Pages/ListUsersLoans.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyLibrary.Models;
using System.Text.Json;

namespace MyLibrary.GUI.Pages
{
    public class ListUsersLoanModel : PageModel
    {
        public IList<Book> Books { get; set; } = default!;

        public void OnGet(int userid)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:7034/");
            HttpResponseMessage message = client.GetAsync("api/Books/Loans/" + userid).Result;
            string returnText = message.Content.ReadAsStringAsync().Result;
            Books = JsonSerializer.Deserialize<List<Book>>(returnText);
        }
    }
}

MyLibraryGUI/Pages/Listall.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyLibrary.Models;
using System.Text.Json;

namespace MyLibrary.GUI.Pages
{
    public class ListAllModel : PageModel
    {
        public IList<Book> Books { get; set; } = default!;
        
        public void OnGet()
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:7034/");
            HttpResponseMessage message = client.GetAsync("api/Books").Result;
            string returnText = message.Content.ReadAsStringAsync().Result;
            Books = JsonSerializer.Deserialize<List<Book>>(returnText);
        }
    }
}

MyLibraryGUI/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyLibrary.GUI.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<ListAllModel> _logger;

        public PrivacyModel(ILogger<ListAllModel> logger)
        {
           // _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

MyLibraryGUI/Pages/Return.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyLibrary.GUI.Pages
{
    public class ReturnModel : PageModel
    {
        public void OnGet(int book, int user)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:7034/");
            HttpResponseMessage message = client.GetAsync("api/Books/ReturnBook/" + book).Result;
            string returnText = message.Content.ReadAsStringAsync().Result;
        }
    }
}

MyLibraryGUI/Pages/SearchResult.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyLibrary.Models;
using System.Text.Json;

namespace MyLibrary.GUI.Pages
{
    public class SearchModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public IList<Book> Books { get; set; } = default!;
        public void OnGet()
        {
            var SearchString = TempData["SearchString"];
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:7034/");
            HttpResponseMessage message = client.GetAsync("api/Books/"+SearchString).Result;
            string returnText = message.Content.ReadAsStringAsync().Result;
            Books = JsonSerializer.Deserialize<List<Book>>(returnText);
        }
    }
}

MyLibraryGUI/Pages/UsersLoans.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyLibrary.Models;
using System.Text.Json;

namespace MyLibrary.GUI.Pages
{
    public class UsersLoansModel : PageModel
    {
        public IList<Book> Books { get; set; } = default!;
        public void OnGet(int userid)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:7034/");
            HttpResponseMessage message = client.GetAsync("api/Books/Loans/" + userid).Result;
            string returnText = message.Content.ReadAsStringAsync().Result;
            Books = JsonSerializer.Deserialize<List<Book>>(returnText);
        }
    }
}

MyLibraryGUI/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Välkommen</h1>

    <a class="nav-link text-dark" asp-page="/ListAll">Lista alla böcker</a>
    <a class="nav-link text-dark" asp-route-userId="1" asp-page="/ListUsersLoans">Användarens lån</a>

    <form method="post">
        <p>
            Sök bok: <input type="text" asp-for="SearchString" name="SearchString" />
            <input type="submit" value="Sök"/>
        </p>
    </form>

</div>

MyLibraryGUI/Pages/Lend.cshtml
@page
@model MyLibrary.GUI.Pages.LendModel
@{
}
Låna

MyLibraryGUI/Pages/ListUsersLoans.cshtml
@page "/ListUsersLoan"
@using MyLibrary.GUI.Pages
@using MyLibrary.GUI.Models
@model ListUsersLoanModel
@{
    ViewData["Title"] = "Alla lån";
}
<h1>@ViewData["Title"]</h1>

@if(Model.Books.Count != 0)
{
    <table class="table">
        <thead>
        </thead>
        <tbody>
            @foreach (var item in Model.Books)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.BookId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Author)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @await Component.InvokeAsync("ShowReturnLink", new LoanClass { BookId = item.BookId, UserId = 1 })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Inga lån.</p>
}

MyLibraryGUI/Pages/Listall.cshtml
@page "/ListAll"
@using MyLibrary.GUI.Pages
@using MyLibrary.GUI.Models
@model ListAllModel
@{
    ViewData["Title"] = "Alla böcker";
}
<h1>@ViewData["Title"]</h1>

<table class="table">
    <thead>
    </thead>
    <tbody>
        @foreach (var item in Model.Books)
        {   
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BookId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @await Component.InvokeAsync("ShowLoanLink", new LoanClass {BookId = item.BookId, UserId = 1})
                </td>
            </tr>
        }
    </tbody>
</table> 

MyLibraryGUI/Pages/Return.cshtml
@page
@model MyLibrary.GUI.Pages.ReturnModel
@{
}

@* Borde kolla om allt fungerat först...*@

Bok tillbakalämnad!

MyLibraryGUI/Pages/SearchResult.cshtml
@page "/SearchResult"
@using MyLibrary.GUI.Pages
@using MyLibrary.GUI.Models

@model SearchModel
@{
    ViewData["Title"] = "Sökresultat";
}
<h1>@ViewData["Title"]</h1>
<h4>@TempData["Message"]</h4>

<table class="table">
    <thead>
    </thead>
    <tbody>
        @foreach (var item in Model.Books)
        {   
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BookId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @await Component.InvokeAsync("ShowLoanLink", new LoanClass { BookId = item.BookId, UserId = 1 })
                </td>

            </tr>
        }
    </tbody>
</table> 

MyLibraryGUI/Pages/Shared/Components/ShowLoanLink/Default.cshtml
@model MyLibrary.GUI.Models.LinkClass

<a href=@Model.Url?book=@Model.Bookid&user=@Model.Borrowerid>@Model.Text</a>

MyLibraryGUI/Pages/Shared/Components/ShowReturnLink/Default.cshtml
@model MyLibrary.GUI.Models.LinkClass

<a href=@Model.Url?book=@Model.Bookid>@Model.Text</a>

MyLibraryGUI/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyLibraryGUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyLibraryGUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">MyLibraryGUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MyLibraryGUI - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MyLibraryGUI/Pages/UsersLoans.cshtml
@page "/UserLoans"
@using MyLibrary.GUI.Pages
@using MyLibrary.GUI.Models
@model UsersLoansModel
@{
    ViewData["Title"] = "Användarens lån";
}
<h1>@ViewData["Title"]</h1>
<table class="table">
    <thead>
    </thead>
    <tbody>
        @foreach (var item in Model.Books)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BookId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @await Component.InvokeAsync("ShowLoanLink", new LoanClass { BookId = item.BookId, UserId = 1 })
                </td>
            </tr>
        }
    </tbody>
</table> 